### ISSUE TITLE
ua_browser_major_version value of non string, missing ""

### ISSUE THREAD

**Issue by elain** [bungoume/fluent-plugin-ua-parser#3]
example:
"http_length":"713","referer":"-","ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:24.0) Gecko/20100101 Firefox/24.0","ua_browser_family":"Firefox","ua_browser_version":"24.0","ua_browser_major_version":24,"ua_os_family":"Mac OS X","ua_os_version":"10.8","ua_os_major_version":10,"ua_device":"Other"

The output should be：
"http_length":"713","referer":"-","ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:24.0) Gecko/20100101 Firefox/24.0","ua_browser_family":"Firefox","ua_browser_version":"24.0","ua_browser_major_version":24,"ua_os_family":"Mac OS X","ua_os_version":"10.8","ua_os_major_version":“10”,"ua_device":"Other"

**Comment by bungoume** [comment]
I have designed `major_version` to compare versions with ease.
(Example:  `major_version:<8 AND ua_os_family:iOS` )
This is why the column is Number.

ua-parser library only return major_version as number.
https://github.com/ua-parser/uap-core/blob/master/tests/test_os.yaml

If you want to use os_major_version as string,
please convert it or parse `ua_os_version` column.
